version: '3'
services:
  openresty:
    image: openresty/openresty:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./openresty/conf.d:/etc/nginx/conf.d
      - ./ssl:/home/ubuntu/toolwebsite/ssl
    depends_on:
      - flask-app
  flask-app:
    build: .
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./font:/app/font
      - ./static:/app/static
    environment:
      - FLASK_ENV=production
      - MAX_CONTENT_LENGTH=52428800  # 50MB in bytes
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 --timeout 300 app:app
networks:
  default:
    driver: bridge
